<?php
/**
 * DeferredPublish (0.0.1)
 * DeferredPublish publishes a page after a defined amount of time has elapsed using lazycron.
 *
 * @author Ben Byford
 * http://www.benbyford.com
 *
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

 class MarkInPageTree extends WireData implements Module {

 	public static function getModuleInfo() {
 		return array(
 			'title' => "MarkInPageTree",
 			'version' => "0.0.2",
 			'summary' => "Mark pages in page tree by true field",
 			'author' => "Ben Byford",
 			'autoload' => true,
 			'singular' => true
 		);
 	}

 	public function init() {
 		$this->addHook("ProcessPageListRender::getPageLabel", $this, 'hookPageListActions');
 	}

 	public function ___hookPageListActions(HookEvent $event) {
 		$page = $event->arguments[0];
 		$out = "";

 		if($page->is($this->selector)){
 			$icon = $this->iconName != "" ? $this->iconName : "certificate";
 			$out = '<i class="fa '. $icon .'"></i>';
 		}

 		$event->return = $out . $event->return;
 	}
 }
